"""add output_language to settings table

Revision ID: 38292967f3ca
Revises: a912a64b7a86
Create Date: 2025-12-17 22:26:19.564663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '38292967f3ca'
down_revision = 'a912a64b7a86'
branch_labels = None
depends_on = None


def _column_exists(table_name: str, column_name: str) -> bool:
    """Check if column exists"""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    """
    Add output_language column to settings table with default value.
    
    Idempotent: checks if column exists before adding.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    if not _column_exists('settings', 'output_language'):
        op.add_column('settings', sa.Column('output_language', sa.String(length=10), nullable=False, server_default='zh'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'output_language')
    # ### end Alembic commands ###



