"""add mineru_token to settings table

Revision ID: a912a64b7a86
Revises: 003_new_fields
Create Date: 2025-12-17 22:07:23.174881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'a912a64b7a86'
down_revision = '003_new_fields'
branch_labels = None
depends_on = None


def _column_exists(table_name: str, column_name: str) -> bool:
    """Check if column exists"""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    """
    Add mineru_token column to settings table.
    
    Idempotent: checks if column exists before adding.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    if not _column_exists('settings', 'mineru_token'):
        op.add_column('settings', sa.Column('mineru_token', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'mineru_token')
    # ### end Alembic commands ###



